Microsoft Teams Name - Tanvi Ajay Gunjal, Ankita Behura Name - Tanvi Ajay Gunjal Matriculation Number - 7002984 Name - Ankita Behura Matriculation Number - 7002639 Tutor - Redion Xhepa

### Exercise 3 c) (3 points)

This is intended to be a tutorial on PyTorch computation graphs. Your taks is to implement XOR. Each of the 3 subexercises is worth 1 point.

The notebook provides code for you to start with. All necessary functions and classes are already imported. If you are unsure about how to use them, you can consult the corresponding documentation page (for example [torch.matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html)). You may use numpy to define the XOR tables.

In [21]:
# import necessary modules
import torch
import numpy as np # for data preparation
from torch import matmul, sigmoid
from torch.nn import MSELoss # Mean squared error

torch.manual_seed(7)

# number of epochs, learning rate and objective function should be the same for everyone
epochs = 1000
lr = 0.5
criterion = MSELoss()

## 1

Now, as everything is imported, load the data into PyTorch tensors and define the model parameters. Explain the your decisions in 1-2 sentences each:

a) How do you initialize the parameters (all zero, all ones, random distribution etc.)?

What happens if biases are initialized as torch.ones(1)?

b) Which of the variables need gradient tracking? What do you have to do to toggle it in PyTorch?


a- Weights if initialized to all zeros or all ones, then the derivative of loss function w.r.t is the same for every w in W[1]. Biases ,have when initialized to 1's shift the activation function by 1 unit(analogous to a constant in a linear function). If weights are randomly initialized, it is certainly better than above cases. But one thing is when they are mapped to very large values or very low values, then after applying sigmoid , they get mapped to nearly 1's or zeroes. Hence, the slope changes slowly and the network takes long time to learn.

b- If there’s a single input to an operation that requires gradient, its output will also require gradient. Conversely, only if all inputs don’t require gradient, the output also won’t require it. weights(Wi, Wo) and biases(ba,bo) need gradient tracking. we can toggle it using requires_grad = True when defining the weights and bias variables as tensors.

In [22]:
X = torch.tensor([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]
                 ], dtype=torch.float32)
print('X', X)
Y = torch.tensor([[0],[1],[1],[0]], dtype=torch.float32).T
print('Y', Y)

# params
n_input, n_hidden, n_output = 2, 2, 1

W_i = torch.rand(n_input, n_hidden, dtype=torch.float32, requires_grad = True)
print('W_i', W_i)
W_o = torch.rand(n_hidden, n_output, dtype=torch.float32,requires_grad = True)
print('W_o', W_o)

b_a = torch.rand((1, n_hidden), requires_grad = True)
b_o = torch.rand((1, n_output), requires_grad = True)
print('b_a', b_a)
print('b_o', b_o)


X tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
Y tensor([[0., 1., 1., 0.]])
W_i tensor([[0.5349, 0.1988],
        [0.6592, 0.6569]], requires_grad=True)
W_o tensor([[0.2328],
        [0.4251]], requires_grad=True)
b_a tensor([[0.2071, 0.6297]], requires_grad=True)
b_o tensor([[0.3653]], requires_grad=True)


## 2

The next step is to implement a full forward pass of the model. This means you have to implement the computation graph built in a) and present each XOR input once to it.

In [23]:
# TODO: forward pass
def forward(x, W_i, b_a, W_o, b_o):
    z2 = torch.matmul(X, W_i) + b_a
    # activation of hidden layer 
    a2 = torch.sigmoid(z2)
    #a2 = a2.type(torch.long)
    # activation (output) of final layer 
    z2 = torch.matmul(a2, W_o) + b_o
    Y_hat =  torch.sigmoid(z2)
    print(Y_hat)
    return Y_hat

Y_hat = forward(X,W_i,b_a,W_o,b_o)

#loss1 = -torch.mean(Y*torch.log(Y_hat)+(1-Y)*torch.log(1-Y_hat))

loss = criterion(Y, Y_hat) # Loss function
print(loss)




tensor([[0.6837],
        [0.7031],
        [0.6940],
        [0.7107]], grad_fn=<SigmoidBackward>)
tensor(0.2893, grad_fn=<MseLossBackward>)


## 3
Enhance your model by actually doing backpropagation! 

Gradient from W_o, W_i + biases

a) Employ the criterion defined in the first code cell to get a loss value and backpropagate by using the .backward() method. Then, access the gradient information in the tracked variables and perform the update. You can do so for a variable w by:

```python
w.data -= lr*w.grad.data
```

You also need to reset the gradient data after performing the update:

```python
w.grad.data.zero_()
```

You will have to loop over the data set several times to get a nice outcome. If your implementation is correct the values defined above (number of epochs, learning rate) will suffice.

In [24]:

for epoch in range(epochs):
    #TODO: Forward pass
    #TODO: Backward pass
    Y_hat = forward(X,W_i,b_a,W_o,b_o)
    loss = criterion(Y, Y_hat) # Loss function
    print(loss)
    #backward propagation
    loss.requires_grad_(True)
    loss.backward()
    
    # optimise weights    
    with torch.no_grad():
        W_i -= W_i.grad.data * lr
        W_o -= W_o.grad.data * lr
        b_a -= b_a.grad.data * lr
        b_o -= b_o.grad.data * lr
        W_i.grad.zero_()
        W_o.grad.zero_()
        b_a.grad.zero_()
        b_o.grad.zero_()
    H_para = [W_i,W_o,b_a,b_o]
#print the hyperparameters that is weights and biases 
# W_i,b_a,W_o,b_o(scalar) respectively
print('W_i',H_para[0]) 
print('b_a',H_para[1])
print('W_o',H_para[2])
print('b_o',H_para[3])

tensor([[0.6837],
        [0.7031],
        [0.6940],
        [0.7107]], grad_fn=<SigmoidBackward>)
tensor(0.2893, grad_fn=<MseLossBackward>)
tensor([[0.6667],
        [0.6848],
        [0.6761],
        [0.6918]], grad_fn=<SigmoidBackward>)
tensor(0.2824, grad_fn=<MseLossBackward>)
tensor([[0.6502],
        [0.6671],
        [0.6588],
        [0.6735]], grad_fn=<SigmoidBackward>)
tensor(0.2765, grad_fn=<MseLossBackward>)
tensor([[0.6347],
        [0.6502],
        [0.6425],
        [0.6560]], grad_fn=<SigmoidBackward>)
tensor(0.2713, grad_fn=<MseLossBackward>)
tensor([[0.6202],
        [0.6344],
        [0.6271],
        [0.6396]], grad_fn=<SigmoidBackward>)
tensor(0.2670, grad_fn=<MseLossBackward>)
tensor([[0.6068],
        [0.6198],
        [0.6130],
        [0.6244]], grad_fn=<SigmoidBackward>)
tensor(0.2635, grad_fn=<MseLossBackward>)
tensor([[0.5946],
        [0.6064],
        [0.6000],
        [0.6105]], grad_fn=<SigmoidBackward>)
tensor(0.2606, grad_fn=<MseLossBackward>)
tensor

tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5007]], grad_fn=<SigmoidBackward>)
tensor

        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4993],
        [0.5011],
        [0.4988],
      

        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
        [0.5006]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5011],
        [0.4989],
      

tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4994],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor

tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor

tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor(0.2500, grad_fn=<MseLossBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5005]], grad_fn=<SigmoidBackward>)
tensor

b) Now, test your model on all data points! Did it learn?

Yes, it learns by updating the weights and biases and slowly converges towards the desired output.

In [25]:
# TODO: Test
W_i.train = W_i
W_o.train = W_o
b_a.train = b_a
b_o.train = b_o
for x,y in zip(X,Y):
    z2 = torch.matmul(X, W_i.train) + b_a.train
    # activation of hidden layer 
    a2 = torch.sigmoid(z2)
    print('Activation layer -1 output given X input produces a2' ,(x, a2))
    # activation (output) of final layer 
    z2 = torch.matmul(a2, W_o.train) + b_o.train
    Y_pred =  torch.sigmoid(z2)
    print('Activation layer -2 output ', Y_pred)
   


Activation layer -1 output given X input produces a2 (tensor([0., 0.]), tensor([[0.5494, 0.6476],
        [0.7015, 0.7779],
        [0.6745, 0.6894],
        [0.7998, 0.8089]], grad_fn=<SigmoidBackward>))
Activation layer -2 output  tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5004]], grad_fn=<SigmoidBackward>)


c) Finally, print the final weight matrix W_o and the hidden activation for each item. Can you tell what the model does to separate the classes? Would it work without sigmoid activation? Explain your answer in 2-3 sentences.

Yes, we could use other activation functions like tanh function.But we  use sigmoid as the weighted sum of inputs(Wx+b) will get out of hand based on weights updation.The main reason why we use sigmoid function is because it exists between (0 to 1).  The sigmoid function helps to classify the output in a value between 0 and 1 which we can infer to be how confident it is of it being in the class, in binary outcomes (like in our case).


In [26]:
# TODO: print W_o & hidden activation
print(W_o.train)
print(a2)
print(Y_pred)


tensor([[-0.0582],
        [ 0.1126]], requires_grad=True)
tensor([[0.5494, 0.6476],
        [0.7015, 0.7779],
        [0.6745, 0.6894],
        [0.7998, 0.8089]], grad_fn=<SigmoidBackward>)
tensor([[0.4995],
        [0.5010],
        [0.4989],
        [0.5004]], grad_fn=<SigmoidBackward>)
